---
apiVersion: v1
kind: Namespace
metadata:
  name: app1
  labels:
    name: app1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app1_ns-read-access 
  namespace: app1
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app1_ns-full-access 
  namespace: app1
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app1_sa-app1_ns-full-access
  namespace: app1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app1_ns-full-access
subjects:
- kind: ServiceAccount
  namespace: app1:default
  name: app1