---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allowreadingazure
spec:
  volumes:
    - 'hostPath'
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  # Allowing pods to use Azure
  allowedHostPaths:
    - pathPrefix: "/etc/kubernetes/azure.json"
      readOnly: true # only allow read-only mounts
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:unprivileged
  namespace: default
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  resourceNames: ['restricted']
  verbs: ['use']
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:readazure
  namespace: default
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  resourceNames: ['allowreadingazure']
  verbs: ['use']
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
