---
apiVersion: v1
kind: Namespace
metadata:
  name: sachinkundu
  labels:
    name: sachinkundu
    created-by: sakunduATmicrosoftDOTcom
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sachinkundu
  namespace: sachinkundu
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "5"
    requests.storage: "10Gi"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sachinkundu_ns-full-access 
  namespace: sachinkundu
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sachinkundu-sachinkundu_ns-full-access
  namespace: sachinkundu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sachinkundu_ns-full-access
subjects:
- kind: User
  namespace: sachinkundu
  name: e82dcb97-3150-49aa-b1e4-863eb82768a4