---
---
# Source: k8s-cncf-hel-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: servicea-k8s-cncf-hel-demo
  labels:
    app.kubernetes.io/name: k8s-cncf-hel-demo
    helm.sh/chart: k8s-cncf-hel-demo-0.1.0
    app.kubernetes.io/instance: servicea
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: k8s-cncf-hel-demo
    app.kubernetes.io/instance: servicea
---

# Source: k8s-cncf-hel-demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-k8s-cncf-hel-demo
  labels:
    app.kubernetes.io/name: k8s-cncf-hel-demo
    helm.sh/chart: k8s-cncf-hel-demo-0.1.0
    app.kubernetes.io/instance: servicea
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-cncf-hel-demo
      app.kubernetes.io/instance: servicea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-cncf-hel-demo
        app.kubernetes.io/instance: servicea
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: k8s-cncf-hel-demo
          image: "sachinkundu/k8s-cncf-hel-demo:240"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {}
            
          env:
          - name: myVariable
            value: "Hello World"
---

# Source: k8s-cncf-hel-demo/templates/canary.yaml
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: servicea-k8s-cncf-hel-demo
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicea-k8s-cncf-hel-demo
  service:
    port: 5000
  canaryAnalysis:
    interval: 10s
    stepWeight: 5
    threshold: 5
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m
    - name: request-duration
      threshold: 500
      interval: 1m
    webhooks:
      - name: load-test
        url: http://load-tester.default/
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 http://servicea-k8s-cncf-hel-demo:5000/"


